<a href="https://colab.research.google.com/github/punishedchumbucket6000/Diabetes.ipynb/blob/main/Diabetes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__

'2.12.0'

In [ ]:
dataset = pd.read_csv('ann-diabetes.csv')
X = dataset.iloc[:,  1:9].values
y = dataset.iloc[:, 0].values

In [ ]:
print(X)

[[2.00e+00 1.08e+02 6.20e+01 ... 2.52e+01 1.28e-01 2.10e+01]
 [0.00e+00 1.37e+02 6.80e+01 ... 2.48e+01 1.43e-01 2.10e+01]
 [1.00e+00 8.90e+01 6.60e+01 ... 2.81e+01 1.67e-01 2.10e+01]
 ...
 [7.00e+00 1.42e+02 6.00e+01 ... 2.88e+01 6.87e-01 6.10e+01]
 [1.00e+01 1.01e+02 7.60e+01 ... 3.29e+01 1.71e-01 6.30e+01]
 [9.00e+00 1.34e+02 7.40e+01 ... 2.59e+01 4.60e-01 8.10e+01]]


In [ ]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0
 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0
 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0
 0 1 0 0 0 0 0 0 0 1 1 0 1 0 0 1 1 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0
 0 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0 1 0 0 0 1 0 1 1
 0 1 1 0 0 1 0 0 1 0 1 1 1 1 1 0 0 0 0 0 1 0 0 0 1 1 0 1 1 1 0 0 1 1 0 1 1
 0 0 0 1 1 1 0 0 1 0 1 0 1 1 0 1 1 1 0 0 1 0 0 0 1 0 0 1 1 1 0 0 1 1 1 1 0
 1 0 0 0 0 0 0 1 0 1 1 0 1 0 0 1 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 0 1 0 1 0 0
 1 1 1 1 1 0 1 1 1 0 1 0 0 1 1 0 1 1 1 0 1 0 1 1 0 0 1 0 0 0 1 1 1 1 0 1 1
 1 1 1 1 1 1 1 1 0 1 0 1 1 1 1 0 1 0 1 0 0 0]


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
ann = tf.keras.models.Sequential()

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [ ]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [ ]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [ ]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
10/10 [==============================] - 1s 4ms/step - loss: 0.5914 - accuracy: 0.6837
Epoch 2/100
10/10 [==============================] - 0s 2ms/step - loss: 0.5761 - accuracy: 0.6837
Epoch 3/100
10/10 [==============================] - 0s 3ms/step - loss: 0.5629 - accuracy: 0.6837
Epoch 4/100
10/10 [==============================] - 0s 2ms/step - loss: 0.5516 - accuracy: 0.6837
Epoch 5/100
10/10 [==============================] - 0s 3ms/step - loss: 0.5404 - accuracy: 0.6837
Epoch 6/100
10/10 [==============================] - 0s 3ms/step - loss: 0.5320 - accuracy: 0.6837
Epoch 7/100
10/10 [==============================] - 0s 2ms/step - loss: 0.5242 - accuracy: 0.6837
Epoch 8/100
10/10 [==============================] - 0s 3ms/step - loss: 0.5177 - accuracy: 0.6837
Epoch 9/100
10/10 [==============================] - 0s 2ms/step - loss: 0.5121 - accuracy: 0.6837
Epoch 10/100
10/10 [==============================] - 0s 2ms/step - loss: 0.5072 - accuracy: 0.6837
Epoch 11/

In [ ]:
print(ann.predict(sc.transform([[2, 100, 75, 20, 100, 25.0, .207, 21]])) )

1/1 [==============================] - 0s 80ms/step
[[0.00693525]]


In [ ]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

3/3 [==============================] - 0s 4ms/step
[[0 1]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [0 1]
 [1 1]
 [1 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [1 0]
 [1 1]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 0]
 [0 1]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]]
